// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9x0N48HC80I30TupBqKnVzd4_DwTUrUU',
    appId: '1:524997680443:web:a58c7f34a13cf6dc442b1e',
    messagingSenderId: '524997680443',
    projectId: 'activitefirebase-235b9',
    authDomain: 'activitefirebase-235b9.firebaseapp.com',
    storageBucket: 'activitefirebase-235b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxWWaKwmGsyvfdiIgnphuHENkKoJY1lPY',
    appId: '1:524997680443:android:a6ec491fb6fc1ead442b1e',
    messagingSenderId: '524997680443',
    projectId: 'activitefirebase-235b9',
    storageBucket: 'activitefirebase-235b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL9iTs1Wr860_pEL4ZGlTuYlUhZn0alqA',
    appId: '1:524997680443:ios:1c4759218e0bce75442b1e',
    messagingSenderId: '524997680443',
    projectId: 'activitefirebase-235b9',
    storageBucket: 'activitefirebase-235b9.firebasestorage.app',
    iosBundleId: 'com.example.activite1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL9iTs1Wr860_pEL4ZGlTuYlUhZn0alqA',
    appId: '1:524997680443:ios:1c4759218e0bce75442b1e',
    messagingSenderId: '524997680443',
    projectId: 'activitefirebase-235b9',
    storageBucket: 'activitefirebase-235b9.firebasestorage.app',
    iosBundleId: 'com.example.activite1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9x0N48HC80I30TupBqKnVzd4_DwTUrUU',
    appId: '1:524997680443:web:988d0da110629245442b1e',
    messagingSenderId: '524997680443',
    projectId: 'activitefirebase-235b9',
    authDomain: 'activitefirebase-235b9.firebaseapp.com',
    storageBucket: 'activitefirebase-235b9.firebasestorage.app',
  );
}
